export const FETCH_USER_REGISTER = "FETCH_USER_REGISTER";
export const FETCH_USER_LOGIN = "FETCH_USER_LOGIN";
export const FETCH_USER_LOGOUT = "FETCH_USER_LOGOUT";
export const FETCH_USER_SUCCESS = "FETCH_USER_SUCCESS";

export const FETCH_USER_ERROR = "FETCH_USER_ERROR";
export const FORM_USER_ERROR = "FORM_USER_ERROR";
